inputs:
  DBMS:
    required: true
    default: "mysql"
  CLUSTER:
    required: true
  SECRETS_JSON:
    required: true
  ACTION:
    required: true
    default: "create"
    description: "create, delete, import or export"
  PREFIX_NAME:
    required: true
  DB_USER:
    required: true
  DB_NAME:
    required: true
  DUMP_FILENAME:
    required: true
    # without sql.gz extension
    default: "latest"
  DUMP_SUBSTITUTIONS:
    required: true
    default: "[]"
    description: "json array of search/replacement to apply before inserting dump (or inverted during dump). This must not contains # (used as sed delimiter)"

runs:
  using: "composite"
  steps:
    ## For debug only
    #- shell: bash
    #  run: |
    #    base64 <<EOF
    #    ${{ toJSON(inputs) }}
    #    EOF
    #- shell: bash
    #  run: |
    #    env | sort
    - shell: bash
      # a checkout action of `coopTilleuls/action-database` must be set with `path: 'action-database'`
      run: |
        set -e
        cd action-database
        test -f cloud_sql_proxy || wget -nv https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
        test -x cloud_sql_proxy || chmod +x cloud_sql_proxy
        bash script.sh
      env:
        SECRETS_JSON: ${{ inputs.SECRETS_JSON }}
        DBMS: ${{ inputs.DBMS }}
        ACTION: ${{ inputs.ACTION }}
        CLUSTER: ${{ inputs.CLUSTER }}
        PREFIX_NAME: ${{ inputs.PREFIX_NAME }}
        DB_USER: ${{ inputs.DB_USER }}
        DB_NAME: ${{ inputs.DB_NAME }}
        DUMP_FILENAME: ${{ inputs.DUMP_FILENAME }}
        DUMP_SUBSTITUTIONS: ${{ inputs.DUMP_SUBSTITUTIONS }}
